
project_id = "imeqkwkvaftgkmcwnhsu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
port = 54325

[realtime]
enabled = true
port = 54326

[storage]
enabled = true
port = 54327

[functions]
[functions.create-checkout-session]
verify_jwt = true

[functions.create-portal-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
